# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 03:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerofactorriegopt',
            name='numero',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
        ),
    ]
