# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 06:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0002_auto_20161201_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numerofactorriegopt',
            name='primer_trimestre',
        ),
        migrations.AddField(
            model_name='primertrimestre',
            name='numero_factores_diabetes',
            field=models.CharField(default=-1, max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tercertrimestre',
            name='fecha_VIH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tercertrimestre',
            name='reactivo_VIH',
            field=models.CharField(choices=[('Reactivo', 'Reactivo'), ('No reactivo', 'No reactivo')], default='No reactivo', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factoresriesgodgst',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='citologia_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='fecha_paraclinicos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='fecha_postest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='odontologia_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='pretest_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='ecografia_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='frotis_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='toxoplasmosis_IGG',
            field=models.CharField(choices=[('IGG Positiva', '|'), ('IGG Negativa', 'IGG Negativa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='toxoplasmosis_IGM',
            field=models.CharField(choices=[('IGM Positiva', 'IGM Positiva'), ('IGM Negativa', 'IGM Negativa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='segundotrimestre',
            name='ecografia_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tercertrimestre',
            name='ecografia_unica_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NumeroFactorRiegoPT',
        ),
    ]
