# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0003_auto_20161203_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestante',
            name='confiable',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='DPTa',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='iami',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='micronutrientes',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
