# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0004_auto_20161203_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='primertrimestre',
            name='fecha_factores_diabetes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
