# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 17:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0010_segundotrimestre_fecha_factores_riesgo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestante',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='gestante',
            name='edad',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Pendiente', 'Pendiente'), ('Atendida', 'Atendida')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='info_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(blank=True, choices=[('Fechaparto', 'Fecha parto'), ('Reciennacido', 'Recien nacido'), ('Puerperio', 'Puerperio'), ('CrecimientoyDesarrollo', 'Crecimiento y Desarrollo'), ('PlanificacionFamiliar', 'Planificaci\xf3n Familiar')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='captacion',
            field=models.CharField(choices=[('M\xe9dico', 'M\xe9dico'), ('Enfermera', 'Enfermera'), ('Atenci\xf3n', 'Atenci\xf3n primaria en salud')], max_length=40),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='fecha_probable_parto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='fecha_ultima_menstruacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestante',
            name='identificacion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='listamotivoschpt',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listamotivosfrotispt',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primercontrol',
            name='citologia_resultado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='RH',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='VDRL',
            field=models.CharField(blank=True, choices=[('Reactivo', 'Reactivo'), ('NoReactivo', 'No reactivo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='VIH',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Reactivo', 'Reactivo'), ('NoReactivo', 'No reactivo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='antigeno_hepatitisB',
            field=models.CharField(blank=True, choices=[('Reactivo', 'Reactivo'), ('NoReactivo', 'No reactivo'), ('Pendiente', 'Pendiente')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='ecografia_semanas',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='estado_factores_diabetes',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='factores_riesgo_diabetes_gestacional',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='frotis_tipo',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='micronutrientes',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='parcial_orina',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Tratamiento', 'En tratamiento')], max_length=40),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='toxoplasmosis_IGG',
            field=models.CharField(blank=True, choices=[('IGGPositiva', 'IGG Positiva'), ('IGGNegativa', 'IGG Negativa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='toxoplasmosis_IGM',
            field=models.CharField(blank=True, choices=[('IGMPositiva', 'IGM Positiva'), ('IGMNegativa', 'IGM Negativa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='segundotrimestre',
            name='VDRL',
            field=models.CharField(blank=True, choices=[('Reactivo', 'Reactivo'), ('NoReactivo', 'No reactivo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='segundotrimestre',
            name='ecografia_semanas',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
        ),
        migrations.AlterField(
            model_name='segundotrimestre',
            name='estado_factores_diabetes',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='segundotrimestre',
            name='factores_riesgo_diabetes_gestacional',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='segundotrimestre',
            name='micronutrientes',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='segundotrimestre',
            name='parcial_horina',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Tratamiento', 'En tratamiento')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tercertrimestre',
            name='VDRL',
            field=models.CharField(blank=True, choices=[('Reactivo', 'Reactivo'), ('NoReactivo', 'No reactivo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tercertrimestre',
            name='ecografia_unica_semanas',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
        ),
        migrations.AlterField(
            model_name='tercertrimestre',
            name='factores_riesgo_VIH',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tercertrimestre',
            name='micronutrientes',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tercertrimestre',
            name='parcial_orina',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Tratamiento', 'En tratamiento')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tercertrimestre',
            name='reactivo_VIH',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Reactivo', 'Reactivo'), ('NoReactivo', 'No reactivo')], max_length=40, null=True),
        ),
    ]
