# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0011_auto_20161213_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestante',
            name='EPS',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
