# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 03:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cita', models.CharField(choices=[('Fecha parto', 'Fecha parto'), ('Recien nacido', 'Recien nacido'), ('Puerperio', 'Puerperio'), ('Crecimiento y Desarrollo', 'Crecimiento y Desarrollo'), ('Planificaci\xf3n Familiar', 'Planificaci\xf3n Familiar')], max_length=40)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida')], max_length=15)),
                ('fecha', models.DateField()),
                ('info_adicional', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FactoresRiesgoDGST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gestante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso_programa', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('identificacion', models.CharField(max_length=15)),
                ('captacion', models.CharField(choices=[('M\xe9dico', 'M\xe9dico'), ('Enfermera', 'Enfermera'), ('Atenci\xf3n primaria en salud', 'Atenci\xf3n primaria en salud')], max_length=40)),
                ('semana_ingreso', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')])),
                ('fecha_ultima_menstruacion', models.DateField()),
                ('fecha_probable_parto', models.DateField()),
                ('confiable', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ListaMotivosCHPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaMotivosFrotisPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NumeroFactorRiegoPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NumeroFactorRiesgoST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.Gestante')),
            ],
        ),
        migrations.CreateModel(
            name='PrimerControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_paraclinicos', models.DateField()),
                ('micronutrientes', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('pretest_fecha', models.DateField()),
                ('fecha_postest', models.DateField()),
                ('iami', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('odontologia_fecha', models.DateField()),
                ('citologia_fecha', models.DateField()),
                ('citologia_resultado', models.TextField()),
                ('DPTa', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.Gestante')),
            ],
        ),
        migrations.CreateModel(
            name='PrimerTrimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuadro_hematico', models.CharField(choices=[('Normal', 'Normal'), ('Anormal', 'Anormal')], max_length=10)),
                ('parcial_orina', models.CharField(choices=[('Normal', 'Normal'), ('En tratamiento', 'En tratamiento')], max_length=40)),
                ('RH', models.TextField()),
                ('VDRL', models.CharField(choices=[('Reactivo', 'Reactivo'), ('No reactivo', 'No reactivo')], max_length=20)),
                ('VIH', models.CharField(choices=[('Reactivo', 'Reactivo'), ('No reactivo', 'No reactivo')], max_length=20)),
                ('frotis_fecha', models.DateField()),
                ('frotis_tipo', models.CharField(choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=15)),
                ('factores_riesgo_diabetes_gestacional', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('ecografia_fecha', models.DateField()),
                ('ecografia_semanas', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')])),
                ('micronutrientes', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('antigeno_hepatitisB', models.CharField(choices=[('Reactivo', 'Reactivo'), ('No reactivo', 'No reactivo'), ('Pendiente', 'Pendiente')], max_length=15)),
                ('toxoplasmosis_IGG', models.CharField(choices=[('IGG Positiva', 'IGG Positiva'), ('IGG Negativa', 'IGG Negativa')], max_length=20)),
                ('toxoplasmosis_IGM', models.CharField(choices=[('IGM Positiva', 'IGG Positiva'), ('IGM Negativa', 'IGG Negativa')], max_length=20)),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.Gestante')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('primerControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.PrimerControl')),
            ],
        ),
        migrations.CreateModel(
            name='SegundoTrimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VDRL', models.CharField(choices=[('Reactivo', 'Reactivo'), ('No reactivo', 'No reactivo')], max_length=20)),
                ('parcial_horina', models.CharField(choices=[('Normal', 'Normal'), ('En tratamiento', 'En tratamiento')], max_length=40)),
                ('factores_riesgo_diabetes_gestacional', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('ecografia_fecha', models.DateField()),
                ('ecografia_semanas', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')])),
                ('micronutrientes', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.Gestante')),
            ],
        ),
        migrations.CreateModel(
            name='TercerTrimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VDRL', models.CharField(choices=[('Reactivo', 'Reactivo'), ('No reactivo', 'No reactivo')], max_length=20)),
                ('parcial_orina', models.CharField(choices=[('Normal', 'Normal'), ('En tratamiento', 'En tratamiento')], max_length=40)),
                ('factores_riesgo_VIH', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('ecografia_unica_semanas', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')])),
                ('ecografia_unica_fecha', models.DateField()),
                ('micronutrientes', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=3)),
                ('gestante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.Gestante')),
            ],
        ),
        migrations.AddField(
            model_name='numerofactorriesgost',
            name='segundo_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.SegundoTrimestre'),
        ),
        migrations.AddField(
            model_name='numerofactorriegopt',
            name='primer_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.PrimerTrimestre'),
        ),
        migrations.AddField(
            model_name='listamotivosfrotispt',
            name='primer_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.PrimerTrimestre'),
        ),
        migrations.AddField(
            model_name='listamotivoschpt',
            name='primer_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.PrimerTrimestre'),
        ),
        migrations.AddField(
            model_name='factoresriesgodgst',
            name='segundo_trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.SegundoTrimestre'),
        ),
        migrations.AddField(
            model_name='cita',
            name='gestante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestantes.Gestante'),
        ),
    ]
