# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0005_primertrimestre_fecha_factores_diabetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primertrimestre',
            name='fecha_factores_diabetes',
        ),
        migrations.AddField(
            model_name='primertrimestre',
            name='factores_diabetes_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
