# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 21:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0007_auto_20161203_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoresriesgodgst',
            name='segundo_trimestre',
        ),
        migrations.AddField(
            model_name='primertrimestre',
            name='estado_factores_diabetes',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='segundotrimestre',
            name='estado_factores_diabetes',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Alterado', 'Alterado')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='segundotrimestre',
            name='fecha_factores_diabetes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segundotrimestre',
            name='numero_factores_diabetes',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='numero_factores_diabetes',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo se permiten n\xfameros')]),
        ),
        migrations.AlterField(
            model_name='primertrimestre',
            name='toxoplasmosis_IGG',
            field=models.CharField(choices=[('IGG Positiva', 'IGG Positiva'), ('IGG Negativa', 'IGG Negativa')], max_length=20),
        ),
        migrations.DeleteModel(
            name='FactoresRiesgoDGST',
        ),
    ]
