# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgestantes', '0008_auto_20161203_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numerofactorriesgost',
            name='segundo_trimestre',
        ),
        migrations.DeleteModel(
            name='NumeroFactorRiesgoST',
        ),
    ]
